# fly.toml app configuration file generated for ultimate-ladder-little-shadow-1352 on 2024-06-30T09:45:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ultimate-ladder-little-shadow-1352'
primary_region = 'cdg'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/ultimate_ladder/static'
  url_prefix = '/static/'
